export const colors = [
  // 파스텔톤 계열
  {
    id: 'pastel-pink',
    hex: '#FFD1DC',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'pink',
    brightness: 'light',
  },
  {
    id: 'pastel-peach',
    hex: '#FFEBCD',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'peach',
    brightness: 'light',
  },
  {
    id: 'pastel-lavender',
    hex: '#E6E6FA',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'purple',
    brightness: 'light',
  },
  {
    id: 'pastel-mint',
    hex: '#F0FFF0',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'green',
    brightness: 'light',
  },
  {
    id: 'pastel-blue',
    hex: '#F0F8FF',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'blue',
    brightness: 'light',
  },
  {
    id: 'pastel-yellow',
    hex: '#FFFACD',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'yellow',
    brightness: 'light',
  },
  {
    id: 'pastel-lilac',
    hex: '#C8A2C8',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'purple',
    brightness: 'light',
  },
  {
    id: 'pastel-green',
    hex: '#98FB98',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'green',
    brightness: 'light',
  },
  {
    id: 'pastel-coral',
    hex: '#F4A460',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'coral',
    brightness: 'light',
  },
  {
    id: 'pastel-cream',
    hex: '#FFFDD0',
    koCategory: '파스텔톤',
    category: 'pastel',
    family: 'yellow',
    brightness: 'light',
  },

  // 파랑 계열
  {
    id: 'light-blue',
    hex: '#87CEFA',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'sky',
    brightness: 'medium',
  },
  {
    id: 'sky-blue',
    hex: '#87CEEB',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'sky',
    brightness: 'medium',
  },
  {
    id: 'powder-blue',
    hex: '#B0E0E6',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'sky',
    brightness: 'light',
  },
  {
    id: 'steel-blue',
    hex: '#4682B4',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'steel',
    brightness: 'dark',
  },
  {
    id: 'cadet-blue',
    hex: '#5F9EA0',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'steel',
    brightness: 'medium',
  },
  {
    id: 'navy-blue',
    hex: '#000080',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'navy',
    brightness: 'dark',
  },
  {
    id: 'royal-blue',
    hex: '#4169E1',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'royal',
    brightness: 'medium',
  },
  {
    id: 'cornflower-blue',
    hex: '#6495ED',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'sky',
    brightness: 'medium',
  },
  {
    id: 'medium-blue',
    hex: '#0000CD',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'navy',
    brightness: 'dark',
  },
  {
    id: 'azure',
    hex: '#007FFF',
    koCategory: '파랑 계열',
    category: 'blue',
    family: 'sky',
    brightness: 'medium',
  },

  // 초록 계열
  {
    id: 'pale-green',
    hex: '#98FB98',
    koCategory: '초록 계열',
    category: 'green',
    family: 'lime',
    brightness: 'light',
  },
  {
    id: 'light-green',
    hex: '#90EE90',
    koCategory: '초록 계열',
    category: 'green',
    family: 'lime',
    brightness: 'light',
  },
  {
    id: 'sea-green',
    hex: '#8FBC8F',
    koCategory: '초록 계열',
    category: 'green',
    family: 'sea',
    brightness: 'medium',
  },
  {
    id: 'medium-sea-green',
    hex: '#3CB371',
    koCategory: '초록 계열',
    category: 'green',
    family: 'sea',
    brightness: 'medium',
  },
  {
    id: 'dark-sea-green',
    hex: '#2E8B57',
    koCategory: '초록 계열',
    category: 'green',
    family: 'sea',
    brightness: 'dark',
  },
  {
    id: 'lime-green',
    hex: '#32CD32',
    koCategory: '초록 계열',
    category: 'green',
    family: 'lime',
    brightness: 'medium',
  },
  {
    id: 'forest-green',
    hex: '#228B22',
    koCategory: '초록 계열',
    category: 'green',
    family: 'forest',
    brightness: 'dark',
  },
  {
    id: 'olive-green',
    hex: '#6B8E23',
    koCategory: '초록 계열',
    category: 'green',
    family: 'olive',
    brightness: 'medium-dark',
  },
  {
    id: 'sage-green',
    hex: '#9DC183',
    koCategory: '초록 계열',
    category: 'green',
    family: 'sage',
    brightness: 'light',
  },
  {
    id: 'mint-green',
    hex: '#98FF98',
    koCategory: '초록 계열',
    category: 'green',
    family: 'mint',
    brightness: 'light',
  },

  // 주황/붉은 계열
  {
    id: 'light-salmon',
    hex: '#FFA07A',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'salmon',
    brightness: 'medium',
  },
  {
    id: 'salmon',
    hex: '#FA8072',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'salmon',
    brightness: 'medium',
  },
  {
    id: 'dark-salmon',
    hex: '#E9967A',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'salmon',
    brightness: 'medium-dark',
  },
  {
    id: 'light-coral',
    hex: '#F08080',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'coral',
    brightness: 'medium',
  },
  {
    id: 'indian-red',
    hex: '#CD5C5C',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'coral',
    brightness: 'dark',
  },
  {
    id: 'tomato',
    hex: '#FF6347',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'red',
    brightness: 'medium',
  },
  {
    id: 'orange-red',
    hex: '#FF4500',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'orange',
    brightness: 'medium',
  },
  {
    id: 'coral',
    hex: '#FF7F50',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'coral',
    brightness: 'medium',
  },
  {
    id: 'dark-red',
    hex: '#8B0000',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'red',
    brightness: 'dark',
  },
  {
    id: 'crimson',
    hex: '#DC143C',
    koCategory: '주황/붉은 계열',
    category: 'red',
    family: 'red',
    brightness: 'medium-dark',
  },
];
