name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # optional
          LANGUAGE: Korean
          PROMPT: Please review this code, focusing on code style, readability, performance, security, and optimization issues. Specifically, point out any redundant code or areas that can be improved. Also, check if function and variable names are appropriate, and ensure proper exception handling and error handling. If necessary, recommend refactoring.  Please provide the review in Korean.
          MODEL: gpt-4o-mini
          IGNORE_PATTERNS: /node_modules,*.md # Regex pattern to ignore files, separated by comma
